### PR TITLE
Whitelist entries for review/merge

### PR DESCRIPTION
**Pull request by dnmTX**
For details see: https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/498
Reviewed and determined that it's safe to be whitelisted.

### CODE REVIEW

**Comment by funilrys** [comment]
Please report to https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/498#issue-394867433 about this.

I'm keeping this on hold.

Also @dnmTX in the future please avoid ´www.xxxx.xxx` the system generate/whitelist it automatically :wink:

**Comment by dnmTX** [comment]
> Also @dnmTX in the future please avoid ´www.xxxx.xxx` the system generate/whitelist it automatically 😉

there were already plenty of those there for each one without `www.` so i thought that it's required

**Comment by funilrys** [comment]
Deletion of all `www.` done.

**Comment by dnmTX** [comment]
> Deletion of all www. done.

Enhancements Enhancements 😉

**Pull request closed without merging**
