### PR TITLE
Introduction of `oload.services` (openload mirror domain)

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by dnmTX** [comment]
@funilrys  as we don't really know how many more `oload.*` are coming i think this should call for removal of all of them and adding `RZD oload` instead.
@smed79  what are your thoughts?

**Comment by smed79** [comment]
> what are your thoughts? 

I prefer adding all domains.
I am not a fan of using the wildcard option, at the exception for big **trusted** companies (google, ebay, amazon ...).

**Comment by funilrys** [comment]
Let's keep single for `oload` :+1: Might get its RZD if we get a million of those :)

Merging.

**Comment by dnmTX** [comment]
Agreed. Thank you for your thoughts on the matter 👍

**Pull request merged**
